[tool.pytest.ini_options]

# Avoid this PytestDeprecationWarning: The configuration option "asyncio_default_fixture_loop_scope" is unset.
# The event loop scope for asynchronous fixtures will default to the fixture caching scope.
# Future versions of pytest-asyncio will default the loop scope for asynchronous fixtures to function scope.
# Set the default fixture loop scope explicitly in order to avoid unexpected behavior in the future.
# Valid fixture loop scopes are: "function", "class", "module", "package", "session"
asyncio_default_fixture_loop_scope="function"
